name: fulltime_force_task
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dart_date: ^1.3.2
  easy_refresh: ^3.3.4
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  github: ^9.22.0
  go_router: ^13.1.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter_app_name:
  name: "Fulltime Force Task"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
